### ISSUE TITLE
Each puppet run will try to change pwdalg.cfg

### ISSUE THREAD

**Issue by sergejschelle** [bwilcox/chsec#1]
Hi, i'm using chsec module on AIX 7200.01.01 with Puppet 4.9.4
This is my configuration:
```  
  chsec { 'password_encryption_algorithm':
    ensure     => present,
    file       => '/etc/security/login.cfg',
    stanza     => 'usw',
    attribute  => 'pwd_algorithm',
    value      => 'smd5',
  }

  chsec { 'standard_salted_MD5':
    ensure     => present,
    file       => '/etc/security/pwdalg.cfg',
    stanza     => 'smd5',
    attribute  => 'lpa_options',
    value      => 'std_hash=true',
  }
```
The modification date of the files has not changed since the first run. The module works fine for the login.cfg, but every check for the presence of 'lpa_options' in pwdalg.cfg results in an 'notice' message. This is the message i get each puppet run:
```
Notice: Chsec[standard_salted_MD5](provider=aix): Changed /etc/security/pwdalg.cfg smd5:lpa_options to std_hash=true
Notice: /Stage[main]/Aixmodule/Chsec[standard_salted_MD5]/ensure: created
```
Any idea how to resolve it?

Thanks in advance,
Sergej

**Comment by bwilcox** [comment]
Sergej, 

Something isn't working right when the command is being run.  Can you run puppet in debug mode to see what the command line is?  And run the command line manually to see if there is an error from the os?

I don't have a 7.2 box available to test with.  There may be some slight difference that I'm unaware of.

**Comment by sergejschelle** [comment]
Puppet in debug mode:
```
Debug: Executing: '/usr/bin/lssec -f /etc/security/login.cfg -s usw -a pwd_algorithm'
Debug: Executing: '/usr/bin/lssec -f /etc/security/pwdalg.cfg -s smd5 -a lpa_options'
Debug: Executing: '/usr/bin/chsec -f /etc/security/pwdalg.cfg -s smd5 -a lpa_options=std_hash=true'
Notice: Chsec[standard_salted_MD5](provider=aix): Changed /etc/security/pwdalg.cfg smd5:lpa_options to std_hash=true
Notice: /Stage[main]/Aixmodule/Chsec[standard_salted_MD5]/ensure: created
Debug: /Stage[main]/Aixmodule/Chsec[standard_salted_MD5]: The container Class[Aixmodule] will propagate my refresh event
```
chsec command works well without errors.
Here is lssec output:
```
# lssec -f /etc/security/pwdalg.cfg -s smd5 -a lpa_options
smd5 lpa_options=std_hash=true
```
Do you need some factor facts from me?

**Comment by bwilcox** [comment]
The good news is that on my test server I can see all the manifest always tries to modify lpa_options, even after it has already done so.  Looks like the code that detects the value didn't expect the extra = in there.

I've uploaded a fix to the github project, tagged 0.1.3.  That fixed the issue on my test server.  Please try it and let me know if it works for you.

**Comment by sergejschelle** [comment]
Yes, that fixed the issue on my AIX 7.2 server. Thank you!
Do you update your module on Puppet Forge too?

**Comment by bwilcox** [comment]
Thank you for validating the update, I'll get an update uploaded to the forge this afternoon.

**Comment by bwilcox** [comment]
Updated Forge module.
